from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(
    title="DevStart API starter",
    version="0.1.0",
    description=(
        "Example FastAPI project generated by DevStart.\n\n"
        "Routes:\n"
        "- GET    /           (welcome)\n"
        "- GET    /health\n"
        "- GET    /items\n"
        "- POST   /items\n"
        "- GET    /items/{item_id}\n"
        "- PUT    /items/{item_id}\n"
        "- DELETE /items/{item_id}\n"
    ),
)


# ---------- Pydantic models ----------


class ItemBase(BaseModel):
    """Fields that a client sends when creating/updating an item."""
    name: str
    description: Optional[str] = None


class ItemCreate(ItemBase):
    """Payload for creating a new item (no ID yet)."""
    pass


class ItemUpdate(ItemBase):
    """Payload for updating an existing item.

    In a real app you might make fields optional here and support partial updates.
    """
    pass


class Item(ItemBase):
    """Item returned from the API (includes ID)."""
    id: int


# ---------- Fake in-memory 'database' ----------

# In a real app you would replace this with Postgres queries.
FAKE_DB: List[Item] = []


# ---------- Routes ----------


@app.get("/", tags=["system"])
def root():
    """Simple welcome route."""
    return {
        "message": "Welcome to your DevStart-generated FastAPI project!",
        "docs_url": "/docs",
    }


@app.get("/health", tags=["system"])
def health_check():
    """Simple health check endpoint."""
    return {"status": "ok"}


@app.get("/items", response_model=List[Item], tags=["items"])
def list_items():
    """
    List all items.

    TODO:
    - Replace this with a SELECT query from Postgres.
    """
    return FAKE_DB


@app.post("/items", response_model=Item, status_code=201, tags=["items"])
def create_item(payload: ItemCreate):
    """
    Create a new item.

    TODO:
    - Replace this with an INSERT query into Postgres.
    """
    new_id = len(FAKE_DB) + 1
    item = Item(id=new_id, **payload.dict())
    FAKE_DB.append(item)
    return item


@app.get("/items/{item_id}", response_model=Item, tags=["items"])
def get_item(item_id: int):
    """
    Get a single item by ID.

    TODO:
    - Replace this with a SELECT ... WHERE id = :item_id query.
    """
    for item in FAKE_DB:
        if item.id == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")


@app.put("/items/{item_id}", response_model=Item, tags=["items"])
def update_item(item_id: int, payload: ItemUpdate):
    """
    Update an existing item.

    TODO:
    - Replace this with an UPDATE ... WHERE id = :item_id query.
    """
    for index, existing in enumerate(FAKE_DB):
        if existing.id == item_id:
            updated = Item(id=item_id, **payload.dict())
            FAKE_DB[index] = updated
            return updated

    raise HTTPException(status_code=404, detail="Item not found")


@app.delete("/items/{item_id}", status_code=204, tags=["items"])
def delete_item(item_id: int):
    """
    Delete an item.

    TODO:
    - Replace this with a DELETE ... WHERE id = :item_id query.
    """
    for index, existing in enumerate(FAKE_DB):
        if existing.id == item_id:
            FAKE_DB.pop(index)
            return

    raise HTTPException(status_code=404, detail="Item not found")
